Assembly guide - detailed 3d object information
index-machines/index pull request #305
Opened 2021-05-04 16:27 UTC by stuartpittaway

Dynamically generates a mark down page/table containing all the STL files for the index, along with detailed build information and likely print duration (based on Prusa Slicer settings)

Github action is triggered manually.

2021-05-08 13:33 UTC, daveismith commented
@stuartpittaway - Before I dig into this too much, can you get it to a state where it can be rebased / merged?

2021-05-08 14:02 UTC, stuartpittaway commented
Hi David, this branch is already clean/aligned with the index/assembly branch - is there another repo/branch to compare with?

2021-05-10 00:32 UTC, daveismith requested changes

2021-05-10 00:32 UTC, daveismith commented on pnp/cad/slice-3d-files.py
> +	proc=subprocess.Popen(["/home/runner/work/index/index/PrusaSlicer.AppImage","--rotate","180","--load","PrusaSlicerConfig.ini","--info","--output",base+"_{used_filament}_{extruded_volume}_{print_time
Given https://docs.indexmachines.io/docs/reference/print-settings/ indicates different settings depending on the part, it seems like there needs to be some more complex logic here to properly estimate the print times.

2021-05-10 11:07 UTC, stuartpittaway commented on pnp/cad/slice-3d-files.py
> +	proc=subprocess.Popen(["/home/runner/work/index/index/PrusaSlicer.AppImage","--rotate","180","--load","PrusaSlicerConfig.ini","--info","--output",base+"_{used_filament}_{extruded_volume}_{print_time
Good point, I doubt there is anyway to tag the various FDM modules/files with that information.  We could also do with rotation information to ensure the model is correctly orientated (this would also apply to the image generation I did for https://docs.indexmachines.io/docs/reference/fdm/)

Any suggestions/recommendations on applying some sort of tag to the FDM files?

2021-05-10 11:16 UTC, stuartpittaway commented on pnp/cad/slice-3d-files.py
> +	proc=subprocess.Popen(["/home/runner/work/index/index/PrusaSlicer.AppImage","--rotate","180","--load","PrusaSlicerConfig.ini","--info","--output",base+"_{used_filament}_{extruded_volume}_{print_time
As a suggestion, you can add custom properties to the FreeCad models - I've just added this one for example to try it.

Although that then brings other issues, like how to access those from code?

![image](https://user-images.githubusercontent.com/1201909/117651049-62bb2580-b189-11eb-8944-263374be1a59.png)

2021-05-11 12:35 UTC, daveismith commented on pnp/cad/slice-3d-files.py
> +	proc=subprocess.Popen(["/home/runner/work/index/index/PrusaSlicer.AppImage","--rotate","180","--load","PrusaSlicerConfig.ini","--info","--output",base+"_{used_filament}_{extruded_volume}_{print_time
@sphawes - is there some way to add some metadata into the various files which indicates which print profile should be used? For the print orientation, I think @Jnesselr has made the suggestion of a named datum plane to indicate the print orientation.

2021-05-17 19:58 UTC, sphawes commented on pnp/cad/slice-3d-files.py
> +	proc=subprocess.Popen(["/home/runner/work/index/index/PrusaSlicer.AppImage","--rotate","180","--load","PrusaSlicerConfig.ini","--info","--output",base+"_{used_filament}_{extruded_volume}_{print_time
@daveismith I'm not sure! for the purposes of a print time estimate, I don't think it's necessary to be this detailed. probably quite a bit of variation between printers/materials anyway. but for actually having folks know how strong to print things, putting that information in the docs would probably be sufficient!

2021-05-17 20:02 UTC, daveismith commented on pnp/cad/slice-3d-files.py
> +	proc=subprocess.Popen(["/home/runner/work/index/index/PrusaSlicer.AppImage","--rotate","180","--load","PrusaSlicerConfig.ini","--info","--output",base+"_{used_filament}_{extruded_volume}_{print_time
@sphawes - In terms of indicating which print config to use, would you imagine that as part of this page (ie, we call out for each part if it's a regular or gantry part? I can see doing this as either a property of the model in FreeCAD if we can figure that one out, or just having a CSV or JSON file that has each part listed along with the info about which type it is.

2021-05-17 20:45 UTC, stuartpittaway commented
Let's close this one out as not needed/bad idea.

2021-05-17 20:45 UTC, closed without merging

2021-05-17 22:06 UTC, daveismith commented
@stuartpittaway - @sphawes  and I quite like it and think it's a nice idea. It could just be slightly improved ;). We would be glad the feature.

2021-05-17 22:16 UTC, stuartpittaway commented
> @stuartpittaway - @sphawes and I quite like it and think it's a nice idea. It could just be slightly improved ;). We would be glad the feature.

Happy to resubmit, but it needs some more work. Noticed @sphawes has put some printing datum planes on some of the new 3d models, so perhaps that can be incorporated at the same time

2021-05-18 07:30 UTC, G-Pereira commented
@stuartpittaway this is really handy to know how much filament people need to buy as well!

About the printing orientation, that will be done in the STL exports so for this script you can assume the STL is already correctly oriented.